export const REGEX_PHONE_CHARACTERS = /(\D)/gm;
export const LENGTH_PHONE_WITHOUT_DDD = 8;
export const LENGTH_PHONE_WITH_CELLPHONE_DIGIT = 9;
export const LENGTH_PHONE_WITH_DDD = 10;
export const LENGTH_PHONE_WITH_DDD_AND_CELLPHONE_DIGIT = 11;
export const LENGTH_PHONE_COMPLETE_WITHOUT_CELL_PHONE_DIGIT = 12;
export const LENGTH_PHONE_COMPLETE_WITH_CELL_PHONE_DIGIT = 13;
