/**
 * Gakkou Service
 * The Gakkou Service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface Aluno { 
    id: string;
    nome: string;
    dataNascimento: string;
    RG: string;
    OrgaoEmissor: string;
    CPF: number;
    nacionalidade: string;
    naturalidade: string;
    profissao: string;
    pai: string;
    mae: string;
    descendencia: string;
    socioANBG: boolean;
    endereco: string;
    setor: string;
    cep: number;
    cidade: string;
    uf: string;
    telefone: number;
    celular: number;
    email: string;
    jaEstudouJapones: boolean;
    ondeEstudouJapones: string;
    conversacao: string;
    hiragana: string;
    katakana: string;
    kanji: string;
    comoSoubeDaEscola: string;
    anoDeIngresso: number;
    semestreDeIngresso: number;
    situacaoDoCurso: string;
    familiaresMatriculadosNaEscola: Array<string>;
    JLPTResults: Array<string>;
    turmaAtual: string;
}

