/**
 * Gakkou Service
 * The Gakkou Service API description
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface FamiliarMatriculado {
  id?: object;
  nome: string;
  parentesco: FamiliarMatriculado.ParentescoEnum;
}
export namespace FamiliarMatriculado {
  export type ParentescoEnum =
    | 'Avó'
    | 'Avô'
    | 'Cunhada'
    | 'Cunhado'
    | 'Esposa'
    | 'Esposo'
    | 'Filha'
    | 'Filho'
    | 'Irmã'
    | 'Irmão'
    | 'Mãe'
    | 'Pai'
    | 'Prima'
    | 'Primo'
    | 'Sobrinha'
    | 'Sobrinho'
    | 'Tia'
    | 'Tio';
  export const ParentescoEnum = {
    AvoMulher: 'Avó' as ParentescoEnum,
    AvoHomem: 'Avô' as ParentescoEnum,
    Cunhada: 'Cunhada' as ParentescoEnum,
    Cunhado: 'Cunhado' as ParentescoEnum,
    Esposa: 'Esposa' as ParentescoEnum,
    Esposo: 'Esposo' as ParentescoEnum,
    Filha: 'Filha' as ParentescoEnum,
    Filho: 'Filho' as ParentescoEnum,
    Irma: 'Irmã' as ParentescoEnum,
    Irmao: 'Irmão' as ParentescoEnum,
    Mae: 'Mãe' as ParentescoEnum,
    Pai: 'Pai' as ParentescoEnum,
    Prima: 'Prima' as ParentescoEnum,
    Primo: 'Primo' as ParentescoEnum,
    Sobrinha: 'Sobrinha' as ParentescoEnum,
    Sobrinho: 'Sobrinho' as ParentescoEnum,
    Tia: 'Tia' as ParentescoEnum,
    Tio: 'Tio' as ParentescoEnum,
  };
}
