/**
 * Gakkou Service
 * The Gakkou Service API description
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface JLPT { 
    id?: object;
    nivel: JLPT.NivelEnum;
    ano: number;
    pontuacao?: number;
}
export namespace JLPT {
    export type NivelEnum = 'N1' | 'N2' | 'N3' | 'N4' | 'N5';
    export const NivelEnum = {
        N1: 'N1' as NivelEnum,
        N2: 'N2' as NivelEnum,
        N3: 'N3' as NivelEnum,
        N4: 'N4' as NivelEnum,
        N5: 'N5' as NivelEnum
    };
}


